http {
    upstream onyx_api {
        server localhost:5000;
        server localhost:5001; # একাধিক সার্ভার একসাথে চালানো (Load Balancing)
    }

    server {
        listen 80;
        location / {
            proxy_pass http://onyx_api;
        }
    }
}